### ISSUE TITLE
interpretor get() throws exception

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#284]
The interpretor `get("name")` method is throwing an
exception.

This previously worked on bsh1.2b7, and does not work
on bsh2.0b1.  I am using j2sdk1.4.2-b28 under win2k.

In my environment I have an unpackaged class named
Topology.  I queried the interpretor for a variable
named `topology` (which had not previously been
defined).  I expected that the interpreter would return
a null value.  Instead it threw the following exception:

> Exception of type=java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: topology \(wrong name:
Topology\)
at java.lang.ClassLoader.defineClass0\(Native
Method\)
at
java.lang.ClassLoader.defineClass\(ClassLoader.java:537\)
at
java.security.SecureClassLoader.defineClass\(SecureClassLoader.java:12
3\)
at
java.net.URLClassLoader.defineClass\(URLClassLoader.java:251\)
at
java.net.URLClassLoader.access$100\(URLClassLoader.java:55\)
at
java.net.URLClassLoader$1.run\(URLClassLoader.java:194\)
at
java.security.AccessController.doPrivileged\(Native Method\)
at
java.net.URLClassLoader.findClass\(URLClassLoader.java:187\)
at
java.lang.ClassLoader.loadClass\(ClassLoader.java:289\)
at
sun.misc.Launcher$AppClassLoader.loadClass\(Launcher.java:274\)
at
java.lang.ClassLoader.loadClass\(ClassLoader.java:235\)
at
java.lang.ClassLoader.loadClassInternal\(ClassLoader.java:302\)
at java.lang.Class.forName0\(Native Method\)
at java.lang.Class.forName\(Class.java:219\)
at
bsh.classpath.ClassManagerImpl.plainClassForName\(Unknown
Source\)
at
bsh.classpath.ClassManagerImpl.classForName\(Unknown Source\)
at bsh.NameSpace.classForName\(Unknown Source\)
at bsh.NameSpace.getClassImpl\(Unknown Source\)
at bsh.NameSpace.getClass\(Unknown Source\)
at bsh.Name.consumeNextObjectField\(Unknown Source\)
at bsh.Name.toObject\(Unknown Source\)
at bsh.Name.toObject\(Unknown Source\)
at bsh.NameSpace.get\(Unknown Source\)
at bsh.Interpreter.get\(Unknown Source\)

It looks to me like the interpreter cannot find the
variable \(ok\) so instead is trying to load the class 
\(probably due to Win2k brain-damage about case
sensitivity in file names\), and then realizing that
this is not what it expected it to be.

This is new behaviour for me.  I did not realize that
autoload behaviour applied to interpreter variables, or
that there was a perfect mapping between objects in the
classpath and objects in the interpretor namespace.

Reported by: opeongo

Original Ticket: "beanshell/bugs/146":https://sourceforge.net/p/beanshell/bugs/146

**Comment by opeongo** [comment]
heh, heh, reported by openogo in 2003...

This is still a weird one that bites me every once in a while.

Imagine that you have a class (Topology) that is not in a package, and this class is on the classpath.  Then try to reference a variable that has the same name as the class, but a different capitalization ("topology").  BeanShell will try to load the class of the same name.  During the load procedure the classloader will detect that the internal classname (Topology) is not the same as the name that was used to lookup up the class (topology), and an error is thrown.

So if BeanShell cannot find an existing name in the namespace it will ask the classloader if it can find the name.  Because the Microsoft Windows file systems are case insensitive a class file is found and the load is attempted and fails.

I guess this is the expected behaviour, but since the values looked up by the Microsoft file systems don't exactly match the values expected by the Java classloader errors will occur.

I suspect that nothing can be done within BeanShell to remedy this, because any fix would potentially mask real problems.

The 'bug' is that there is that the Windows file systems are deficient with respect to the requirements of the Java classloader.  This is out of scope of the BeanShell project.

Sadly I think I have to live with this one.  By the way, in some situations this also manifests with classes that are in packages, so I have had to be quite careful about conflicts between variable and class names.

**Comment by nickl-** [comment]
I think we should look into this some more and can ensure that Windows works as the case sensitive file systems do. BeanShell correctly treats the class name as case sensitive as JAVA does.

@opeongo can you give a code snippet to produce the error please. Then I will test and see what happens on other OS.

Tx for all the help!!!

**Comment by nickl-** [comment]
> The 'bug' is that there is that the Windows file systems are deficient with respect to the requirements of the Java classloader. This is out of scope of the BeanShell project.

As per OP's instruction, closed: out of scope
